server:
  app:
    name: bff-service
    version: v1.0.0
  Port: :8000
  ReadTimeout: 5
  WriteTimeout: 300
  JwtSecretLocation: /mnt/secrets-store/jwt_secret
  AesEncryptionSecretLocation : /mnt/secrets-store/aes_encryption_secret
  JwtSecret: 4fg88hsdf04ea6f26e3d1d3c5f17aba9770fab35de1400d7de89212cb2d32e240323f33a261181bd60b779cc97d15affbf6c51128b07c26964911c0b16b155f6c0c4e6f96e55649d03e9cbc7ca9681102e267be067ccb611c6cb35e07612c0449358a1e0cc7f638ac7c228f25e9650d8c6ea72e2619ef5474a11d9733afec91a

AppConfig:
  AppId: fj33jg5
  ConfigName: zv0z0bl
  PollingInterval: 100

lmmRedisSecretLocation: /mnt/secrets-store/elasticache_credentials

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

goPool:
  maxConcurrentRoutines: 200

playlistFilenameConfig:
  hlsFilename: "master.m3u8"
  dashFilename: "dash.mpd"

akamaiConfig:
  BaseURL: https://comms-content.allen.in/
  key: bed553021824f73a2a02c18110871165

whiteListSubTypesForContentAuth :
  subTypes: [PODCASTS, VIDEO_SOLUTIONS]