server:
  app:
    name: bff-service
    version: v1.0.0
  Port: :8000
  ReadTimeout: 5
  WriteTimeout: 300
  JwtSecretLocation: /mnt/secrets-store/jwt_secret
  AesEncryptionSecretLocation : /mnt/secrets-store/aes_encryption_secret
  JwtSecret: 01d3024af90f4100c22d20eb294eee46e8fa286b53a4b08aa16cadf7d4b70b0935778af1228caf115caeb62873f789b7af6f2e6591272cec784d6fc68a91e9f8538a223b8aa622b594cfac2a01ef15fb583d5adadea3174be6cc91d0db638574997334df095427b3319a3937d10c07adc2e4a95669bd1fd75807dd02bca06432

AppConfig:
  AppId: 0k95goc
  ConfigName: 5itjbhl
  PollingInterval: 100

lmmRedisSecretLocation: ""

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

goPool:
  maxConcurrentRoutines: 200

playlistFilenameConfig:
  hlsFilename: "master.m3u8"
  dashFilename: "dash.mpd"

akamaiConfig:
  BaseURL: https://comms-content.allen-demo.in/
  key: 2c88c00ffc129b44e4145a81227b81fa

whiteListSubTypesForContentAuth :
  subTypes: [PODCASTS, VIDEO_SOLUTIONS]