package clients

const (
	AuthenticationServiceClient         = "authenticationServiceConfig"
	CalServiceClient                    = "calServiceConfig"
	CheckoutServiceClient               = "checkoutServiceConfig"
	CheckoutWorkflowServiceClient       = "checkoutWorkflowServiceConfig"
	ClassroomServiceClient              = "classroomServiceConfig"
	ECommWorkflowServiceClient          = "ecommWorkflowServiceConfig"
	DiscoveryServiceClient              = "discoveryServiceConfig"
	LmmServiceClient                    = "learningMaterialConfig"
	LmmRedisClient                      = "learningMaterialRedisConfig"
	LearningJourneyClient               = "learningJourneyConfig"
	QReelsClient                        = "qReelsConfig"
	QuestionBankClient                  = "questionBankConfig"
	FeedbackClient                      = "feedbackConfig"
	QBMigrationClient                   = "qbMigrationConfig"
	ImprovementBookClient               = "improvementBookConfig"
	ListingServiceClient                = "listingServiceConfig"
	OfferServiceClient                  = "offerServiceConfig"
	OrderServiceClient                  = "orderServiceConfig"
	PageServiceClient                   = "pageServiceConfig"
	ResourceServiceClient               = "resourceServiceConfig"
	TaxonomyServiceClient               = "taxonomyServiceConfig"
	UserServiceClient                   = "userServiceConfig"
	PolicyServiceClient                 = "policyServiceConfig"
	NoticeBoardServiceClient            = "noticeBoardServiceConfig"
	NotificationServiceClient           = "notificationServiceConfig"
	DoubtServiceClient                  = "doubtServiceConfig"
	AuthorizationServiceClient          = "authorizationServiceConfig"
	AuthorizationPdpServiceClient       = "authorizationPdpConfig"
	SalesOrchestratorClient             = "SalesOrchestratorConfig"
	ChatServiceConfig                   = "chatServiceConfig"
	TAAAdminClient                      = "taaAdminConfig"
	TAAAacdemicClient                   = "taaAdminConfig"
	TAAStudentClient                    = "taaStudentConfig"
	TAAEngineClient                     = "taaEngineConfig"
	TAAWorkflowClient                   = "taaWorkflowConfig"
	QuestionCollectionClient            = "questionCollectionConfig"
	UserConflictResolutionServiceClient = "userConflictResolutionConfig"
	CareCornerClient                    = "careCornerConfig"
	TemporalClient                      = "temporalClient"
	AttendanceInsightsClient            = "attendanceInsightsClient"
	CustomTestClient                    = "customTestConfig"
	SurveyManagerClient                 = "surveyManagerConfig"
	ExperimentationConfigClient         = "experimentationConfig"
	PlanningAndSchedulingServiceClient  = "planningAndSchedulingConfig"
	UserAttributeStoreConfig            = "userAttributeStoreConfig"
)

const UserClientConnError = "Error while creating grpc connection with user service: %v"
